// The resolve function is used to indicate a successful completion of the operation, 
// and the reject function is used to indicate an error.


/* const myPromise = new Promise((resolve, reject) => {
  // Asynchronous operation here
  if (opsSuccess) {
    resolve(result);
  } else {
    reject(error);
  }
});


myPromise
  .then((result) => {
    // Handle successful result
  })
  .catch((error) => {
    // Handle error
  });
 */

  